JoinMarket-Org/joinmarket

- common.py
- irclib.py
- maker.py
- taker.py
- wallet-tool.py
- yield-generator.py
An option to put all coins back to a single address. Perhaps useful if you want to re-start testing some aspect (although the "used" flags on addresses won't change of course), or to send coins back to the faucet. Debatable I guess, but since it's only an option, I suppose it doesn't hurt.
> add reset option to wallet tool

- common.py
Using the parameter `unconfirmed = 1` stops the output of /address/unspent from containing utxos which are already in a recently pushed (unconfirmed) transaction, so preventing them from appearing in the wallet and causing pushtx() failures. 
Tested briefly (and checked the API output on the web). Seems to work correctly and allow a second  sendpayment to operate while the first is not yet confirmed.
> dont use utxos in existing unconfirmed txs

- joinmarket.cfg
- lib/irc.py
Socks5 proxy support as per #63
> Implemented socks5 proxy

- lib/common.py
```
>>> create_combination(['apple', 'orange', 'pear', 'orange'], 3)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "lib/common.py", line 358, in create_combination
assert len(result) == nCk(len(li), n)
AssertionError
```
> Use itertools.combinations when sweeping

- ob-watcher.py
- orderbook.html
- Converted whole site to bootstrap
- Added "GitHub" and "Getting Started" links in the menubar
- Included "sortable.js" for sorting the table, client side
- Removed server-side table sorting
I hope you accept this pull request because it adds a user front-end to view the inner workings of this project, and it's way more presentable.
> Changed appearance and sortablility of table and website

- ob-watcher.py
I found that 'localhost' didn't cut it for me and I've added a host and port flag.
Note that I'm not a Python programmer. I might have done crazy things.
> Adds flags to specify host/port for ob-watcher.

- lib/common.py
The UTXO selection of BitcoinCoreWallet with fromaccount set did accept also UTXO's without an account.  This is in direct contradiction to the user's wish for a specific account.  With this patch, we really only accept UTXO's that have the specified account set explicitly.
> Fix BitcoinCoreWallet's UTXO selection.

- lib/common.py
[reduced dust threshold to 543, in line with electrum](https://github.com/chris-belcher/joinmarket/commit/652ee06612a750e60d75cec30b8e7160816b4e96)
At minimum, this should be [corrected to 546](https://github.com/bitcoin/bitcoin/blob/master/src/primitives/transaction.h#L146).  
I think maybe it should be a maker cfg option, default set to match core default (546), but I would propose increasing it to approx. 5500 satoshis for these reasons;
1) At today's prices, 546 satoshis is ~$0.0013 USD, and would only be $0.00546 if BTC went to $1000/BTC.  A dust limit of ~5500 would be about $0.01375 at current prices, and $0.055 at $1000/BTC.
2) I think the typical use cases for joinmarket won't involve a lot of these low value ($) transactions.
3) I wouldn't want my wallet cluttered with utxos …
> fix DUST_THRESHOLD typo - Discuss Best Practices

- ob-watcher.py
- yield-generator.py
Fixes #122 except for the testnet stuff.
> Prevents startup spam to log.

- lib/common.py
In the 'pick orders' dialog, display the tx fee contribution in addition to the resulting CJ fee for each order.
I also changed the display formatting a bit, IMHO the new display is more readable as it is "tabular".  If this change is not desired, let me know and I'll revert it and just append the tx fee contribution at the end.
> Display tx fee contribution when picking orders.

- lib/maker.py
Reverts chris-belcher/joinmarket#135
```
File "/home/less/joinmarket/lib/maker.py", line 119, in confirm_callback
to_cancel, to_announce = self.maker.on_tx_confirmed(self, cjorder, confirmations, txid)
NameError: global name 'cjorder' is not defined
```
> Revert "bug fix" (that just introduced another)

- lib/blockchaininterface.py
see http://daniel.haxx.se/docs/curl-vs-wget.html for details
> use curl instead of wget for maximal portability

- lib/blockchaininterface.py
You can check the fix by deleting a zero or two (or three!), and verifying that all your transaction history is loaded in whichever chunk size you choose.
> bugfix: load transactions past the 1Kth

- .travis.yml
- lib/enc_wrapper.py
- test/bitcoin.conf
- test/regtest.py
- test/regtest_joinmarket.cfg
- test/wallet-test.py
Details:
* Test subdirectory created, with supporting files for regression tests:
* regtest_joinmarket.cfg - special config for regtest running, bitcoin.conf - for same, regtest.py same as previous but modified and put under /test
* Travis automated build test support: added .travis.yml to main directory, contains script to build joinmarket on Ubuntu1204 VM and then to run enc_wrapper and regtest scripts (just to start of course).
I've connected Travis to my AdamISZ/joinmarket repo (it uses githooks) and it'll automatically test all pushes to my master branch. The tests are currently passing (You (@chris-belcher) can obviously do the same if and when it seems like a good idea.
Future plans in this regard: not sure what to do first, but probably add tests involving a larger number of bots …
> Add travis for testing, testing files in test directory

- lib/bitcoin/transaction.py
Tested 10000 transactions on regtest with old version: got 44/10000 failures; see http://pastebin.com/u6imE6MC for txhex of each failed tx. A quick way to find the source of the error is to search for the string '021f' (although it could be lower than 1f, but the likelihood of that is near zero).
Tested 10000 with this bip66 correction: got 0/10000 failures (of any type).
The value 44/10000 is closely in line with expectations: 1/(256*2) is the expected probability of this failure mode for one DER encoded value (half of the cases where the first byte of 32 is zero). However, each of these transactions had 1 input, meaning 2 DER encoded values, leading to a 1/256 or ~40/10000 expected number of failures.
Note that all failures were associated with the same error string: "error: …
> fix bip66 issue with signatures

- .gitignore
I setup my app with `virtualenv env; . env/bin/activate; pip install numpy`
This will ignore the env directory. "env" is a pretty standard although sometimes people instead do "pyenv" or ".env"
> alphabatize gitignore and ignore env for virtualenvs

- lib/irc.py
I believe this is a more anonymous and random method and possibly more efficient way to generate random_nick for ircnick.  Thoughts?
> Change how random irc nicknames are generated.

- lib/blockchaininterface.py
Won't have caused a problem yet unless people do something weird, but obv. should be corrected (thread would just exit if these debugs got called).
> fix common.debug calls in notifier

- lib/common.py
- lib/taker.py
- ob-watcher.py
> validate cjfee in OrderbookWatch.on_order_seen

- lib/common.py
update default tor config: 6dvj6v5imhny3anf.onion uses port 6697 and requires ssl authentication currently.
https://cyberguerrilla.info/ways-to-connect-to-cgan-irc/
Tor opens a socks proxy on port 9050 by default
[TBBSocksPort](https://www.torproject.org/docs/faq.html.en#TBBSocksPort)
> update default tor config

- wallet-tool.py
The issue that this addresses starts in #190 and continues/finishes in the [reddit thread](https://www.reddit.com/r/joinmarket/comments/3h0vyy/alert_someone_sent_coins_to_and_has_been_using_a/).
The fix is trivial, just checking that the seed phrase entered is 12 words.  While doing it, I noticed that .split(' ') has the unfortunate effect of treating extra spaces as extra words (so 'a b  c'.split(' ') comes out as ['a',b','','c'] which is undesirable if nothing else because it gives a misleading error). So I've edited it to .split() because this will split on any amount of whitespace, which is a more expected behaviour.
A perhaps more 'meta' conclusion from all this is to look again at sanity checking user input generally, and don't assume that used libraries (slowaes, old_mnemonic) are …
> sanity check length of recovery seed

- lib/common.py
- lib/slowaes.py
PKCS7 padding has the form: 01 or 0202 or 030303 etc. For a correctly entered password and a correct decryption, there will be a full block of padding at the end of the data: 1010... (16 times, hex). This obviously cannot happen by chance, which is why entering an incorrect password throws a ValueError which the current code then interprets as decryption failure and requests the user to try again.
However, in the case where an entered password is incorrect, it is possible that the decrypted data (*before* stripping the padding) ends with ..01. This would be interpreted as correctly pkcs7 padded, the 01 would be stripped, and a decrypted seed of length 32+15 = 47 bytes would be returned. No ValueError would be thrown and then a bip 32 master seed would be correctly (but randomly) …
> ensure correct password

- test/commontest.py
- test/regtest.py
- test/wallet-test.py
- test/wnb.sh
A commontest module for functions such as: populating wallets with coins, dealing with interactive command line input (using pexpect).
The former in particular will help with writing more sophisticated, generic tests (in particular, making sure you can test bots with "messier" wallet structures).
Note that this PR is independent of #187
> refactor tests, small improvements

- ob-watcher.py
cleans up the display of units returned for the orderbook.  only affects decimal output of fees and min/max size display.
see [this display with clean satoshi display](http://bitcoin-p2pool.com/joinmarket_orderbook.html) vs [this current style of display](http://joinmarket.io/)
edit, both of the above are now using (variations of) this PR.
> standardize satoshi_to_unit output

- lib/blockchaininterface.py
- lib/common.py
- lib/jsonrpc.py
Replace the connection to Bitcoin Core via bitcoin-cli by a connection through its JSON-RPC interface.  This is cleaner, as it does not require to convert everything to/from strings.  It is also able to handle error codes.
See https://github.com/chris-belcher/joinmarket/issues/137.
I have tested that it works successfully for a `sendpayment.py` order.  More testing would probably be good, though.
> Implement JSON-RPC interface instead of CLI.

- lib/maker.py
if tx is not broadcast and confirmed on the network, no earnings are made.  "earned = " is more accurate after the tx is in a block.
> "(potentially) earned" phrasing change

- lib/common.py
- tumbler.py
Removed usage of numpy module.
There are a set of of rand_* functions in common which replace the necessary functions. The only slightly complex ones are: first, power law distribution, achieved using the inverse of the cdf, see the wolfram link for the idea. I checked this by looking at sample arrays to see that the number of entries in different bins was approximately the same as that produced by the numpy version. Second, the random-choice-weighted-by-probabilities function, which is done by setting boundaries according to the cumulative array of probabilities and then choosing using a random sampled from a uniform dist. There are floating point inaccuracies here, but as noted in comments that's expected and considered unimportant. If later it's felt to be necessary to remove that, it …
> numpy removal

- lib/common.py
- lib/socks.py
> combat dust thru utxo merge policies

- lib/socks.py
Fixes #220 (thank you @CohibAA for reporting it!)
Appears to have been an upstream bug, which each upstream fork has fixed differently; this fix is ```min```imal.
> Bugfix: socks5 negotiation failure reporting

- lib/taker.py
Intended to address #104 .
Tested it in a few configurations, specifically against cases where the yield gen has 3-6 utxos and verified in the logs that the utxos were bundled and sent to query_utxo_set only once. Also as requested made sure that our own utxos aren't included.
Unfortunately regtest testing doesn't support blockr of course.
> move query_utxo_set out of the loop

- lib/common.py
- lib/irc.py
- lib/taker.py
- patientsendpayment.py
- sendpayment.py
- tumbler.py
Implemented changes suggested in #166
A new thread is started for each CoinJoinTX object, there is a threading condition lock which passes notifications between the two threads. Currently the timeout for maker non-reply is 10 seconds.
If a maker doesn't reply, it will be ignored for the rest of lifetime of the Taker instance.
`sendpayment.py` and `tumbler.py` have been made to work with this.
Testing welcome. I've tested this on regtest with tumbler, it was able to complete it's run even though one maker never responded to either !fill, !auth or !tx
Second attempt at merging, given the derping with the other branch.
Please test, especially let me know if you encounter an unresponsive maker. Watch if the taker handles that in the correct manner.
> Crude recovery by taker from unresponsive makers

- lib/common.py
I spent some time thinking about the right way to handle the issue in #197.
From one angle it looks like a very small problem that's being solved here, because the code already enforces one order being accepted from each counterparty. But as noted, the probabilities are skewed in case the choice algorithm chosen is probabilistic, because the weighting is done before that enforcement. This code uses a Python one liner to take only one order from each counterparty - the one with the lowest calculated coinjoin fee - from each counterparty before doing any selection algorithm. I put an if/else in case someone wants to make a manual choice.
(Btw in case you're wondering, reverse=True *is* correct here - the reason is a bit obscure).
I've done some test runs on a modified branch using …
> consider only 1 order from each counterparty before choosing

- lib/common.py
As per IRC. I did some runs with regtest, and *this* time I checked properly: it is taking one offer within range, and only the best offer, and the output is sorted by price. Previously I had stupidly only checked that it was taking one offer from each, ignoring the order.
> fix of the fix of the fix of the counterparty selection

- lib/blockchaininterface.py
- lib/common.py
When `--rpcwallet` is used and the wallet is locked, ask the user for a passphrase to unlock the wallet before using it.
This only works when using the new JSON-RPC interface instead of the CLI tool.
> Try to unlock RPC wallet if it is locked.

- lib/bitcoin/bci.py
- lib/blockchaininterface.py
Use HTTPS rather than HTTP for API calls to blockr.io and blockchain.info
Fixes #264
> Use HTTPS rather than HTTP

- lib/irc.py
This functionality is [coded](https://github.com/chris-belcher/joinmarket/blob/master/lib/irc.py#L168-L178) [twice](https://github.com/chris-belcher/joinmarket/blob/master/lib/irc.py#L128-L132), but it's done differently in each and this leftover code only serves to confuse.
> Delete unused code: irc_privmsg_size_throttle()

- lib/common.py
It's a bad practice to print the password in plaintext to the log.
> Don't print IRC password to the log when doing a debug_dump_object

- yield-generator.py
This was causing small transactions to be taken from the largest mixing depth instead of the smallest mixing depth.
> taking from highest balance where it was suppose to be lowest

- test/regtest.py
- yield-generator-basic.py
- yield-generator-deluxe.py
- yield-generator-mixdepth.py
This moves the yieldgens into develop. 
The basic yieldgen from master is renamed here to yield-generator-basic.py.
The yieldgen that was in new-yieldgen-algo branch is now yeild-generator-mixdepth.py.
The yieldgen that I developed and was reviewed at https://github.com/JoinMarket-Org/joinmarket/pull/329 , is included here as yield-generator-deluxe.py.
Next these will be moved into their own folder with the includes modified as needed. As a first step, putting them in the top folder where they all work and the files have not been otherwise modified. 
After this is pulled, I will close my previous pull #329, and we can get rid of the new-yeildgen-algo branch. I verified with belcher on irc that the yield-generator.py was the only file modified in the new-yieldgen-algo branch.
> include all yieldgens

- joinmarket/blockchaininterface.py
- joinmarket/configure.py
- wallet-tool.py
This addresses #39 but does not solve it for blockr users.
When using a full node, `wallet-tool.py` will display unconfirmed balances by default, but other scripts won't actually spend them unless that behavior is manually configured.
> add confirmation-spendability knob for bitcoind-rpc

- sendpayment.py
Add the `--gaplimit` option that is present for `wallet-tool.py` also for `sendpayment.py`.
This is https://github.com/JoinMarket-Org/joinmarket/pull/370 rebased onto `develop`.
> Add gaplimit option for sendpayment.py.

- joinmarket/maker.py
- joinmarket/wallet.py
- patientsendpayment.py
- sendpayment.py
- test/commontest.py
- test/fee-estimation.py
- test/tumbler-test.py
- tumbler.py
- wallet-tool.py
- yield-generator-basic.py
- yield-generator-deluxe.py
- yield-generator-mixdepth.py
Fixes #283
Note that this is MORE than a naming change: tumbler.py, maker.py,
and the yield-generator scrypts have been modified to use only the
internal branch, specifically to avoid reuse of receiving address.
> Restructure for_change HD branch as {in,ex}ternal

- yield-generator-basic.py
- yield-generator-deluxe.py
- yield-generator-mixdepth.py
This resolves issues #106 and #358.
Also fixed an issue where the txfee contribution was not being taken account of when filling orders, which could have rarely been causing crashes if the total amount surpassed the utxo selection.
Added dust exact sized absolute offers. 
ygbasic and ygmixdepth both pass regtest
ygdeluxe only passes when its configuration options are greatly simplified so that it only creates a single order. I guess an issue with how the test selects orders. The error being thrown is  https://bpaste.net/show/e82a247f1608
> fixes issues #106 and #358

- joinmarket/blockchaininterface.py
I was stuck for a time with a typo in my notify request that I set up in bitcoin.conf.  This message would have been really helpful to let me know what I should check for when running the project to get past my issue.
> Adding helpful message when an unhandled path is sent to the http notify request

- joinmarket/taker.py
See #390 .
It makes me realise that any protocol 'expansions' have to pay particular attention to on_order_seen.
This is basically assuming that we don't need to catch a valueerror anywhere else based on the value of 'cjfee', as long as we don't let anything invalid come in in the first place.
Minimal testing done, but it seems uncontroversial. ACKs or NACKs appreciated.
> disallow non-integer absorders in on_order_seen

- yield-generator-basic.py
- yield-generator-deluxe.py
- yield-generator-mixdepth.py
With the current 'clumping' oid_to_order code, since it tries to clump into what is already the largest pile, coins wont move through the mixdepths if no large orders come in. Once a small amount of coins leave the largest pile, they will circulate all the way around and end up in the big pile again. I propose the way this should be dealt with is to prioritize by mixdepth number. So that coins in mixdepth0 are spent first, then mixdepth1, and lastly max_mix_depth. This will still tend towards clumping, but always at the last 
mixdepth, causing coins to move through to the max depth when deposited in mixdepth 0.
> clump coins to max mixdepth, dev

- joinmarket/__init__.py
- joinmarket/blockchaininterface.py
- joinmarket/configure.py
- joinmarket/support.py
- joinmarket/taker.py
- ob-watcher.py
adds two global (module) vars in support.py which are referenced in global_singleton in common.py (done this way due to circular references if trying to refer to jm_single from support.py). JoinmarketStreamHandler provided by @chris-belcher
> put back joinmarket alerts and core alerts

- joinmarket/taker.py
certain malicious and/or incompetent liquidity providers send inputs totalling less than the coinjoin amount! this leads to a change output of zero satoshis, so the invalid transaction fails harmlessly; now we fail earlier, with a clear message.
reopens #407 which currently stands at ACK from me, and utACK from @chris-belcher and @AdamISZ
> require liquidity providers to provide liquidity

- yield-generator-deluxe.py
This fixes the default config for deluxe so that users dont initially get joins for only a single satoshi profit.
> fix small profit default config

- yield-generator-mixdepth.py
One edit that moves a line into the if statement.
Aside: How does it happen that maker's don't see the unconfirmed transaction sometimes? It gets relayed to the miners but not to us for some reason.
> Fix crash in yield generator mixdepth when no unconfirm notify arrives

- yield-generator-oscillator.py
YG that dynamically raises or lowers fee based on the users transaction volume, and uses the transaction history from the csv statement. Fee rates are fully configurable by the user. I guessed at some sane defaults. This will benefit the market by rotating less used offers to lower prices, and more used offers to higher prices, diversifying which maker utxos are being used. This solves the problem for the user of having to manually adjust their offer pricing, and allows them to better gather data about their pricing strategy. Included with this, csv files now show entries for 'unconfirmed' transactions which gets updated once they are confirmed. Separate statement tracking for different wallets, csv file name is now yigen-statement-yourwallet.csv. Enhanced mix depth selection, Slinky …
> add yg oscillator

- joinmarket/message_channel.py
- test/test_keys.py
- test/test_regtest.py
- test/test_wallets.py
- test private key formats
- coverage now includes yieldgen/maker code due to graceful subprocess shutdown
- add sweep transaction to regtest tests
- add tests for utxo selection algorithms and pragma no cover for abstract methods
> Several more test improvements including maker coverage

- README.md
- bitcoin/__init__.py
- bitcoin/secp256k1_deterministic.py
- bitcoin/secp256k1_main.py
- bitcoin/secp256k1_transaction.py
- create-unsigned-tx.py
- joinmarket/blockchaininterface.py
- joinmarket/configure.py
- joinmarket/old_mnemonic.py
- joinmarket/taker.py
- joinmarket/wallet.py
- test/commontest.py
- test/test_keys.py
- test/test_mnemonic.py
- test/test_regtest.py
- test/test_wallets.py
- wallet-tool.py
a local version but assuming the binding is installed already with
"pip install secp256k1". Does not yet include an updated form of the
donation code for custom nonces.
add mnemonic tests
Modification so that either secp256k1 or pybtc can be used;
secp256k1 python binding is detected automatically.
NOT YET READY TO MERGE.
Passes test suite currently both with and without secp256k1 module installed on the system.
Tests ongoing. Todo: re-add alternative code for donation tx. Test tumbler and modify if needed (I expect not). Apologies for re-formatting of create-unsigned-tx; will also need some testing there.
Will also need to add warning/info message if secp256k1 is not detected.
> New re-integration of secp256k1 via ludbb binding; no longer using

- test/conftest.py
- test/test_irc_messaging.py
I needed this to make tests work for me
Also added a commented-out `time.sleep(90)` in test_irc_messaging.py which seems to be required for me but not for anyone else. In time we could move to something like #499 
I've tested it and ran it so there shouldn't be any obvious crashes.
> Added option to pass rpc username in tests

- joinmarket/jsonrpc.py
- patientsendpayment.py
- sendpayment.py
- wallet-tool.py
Implementation of #200 
You need to be configured to use Bitcoin Core (-txindex=1 not required), run it with:
`python wallet-tool.py wallet.json history`
Prints a summary for every transaction. If you have numpy/scipy installed it also calculates the effective interest rate you achieved as if yield-generators were a savings account. For my own yield generator wallet the figure is 0.67% per annum
It checks if the amount of bitcoins in the wallet is the same as the resulting amount when added up as iterating through all transactions. It also checks if the number of UTXOs in the wallet match the number found by iterating through transactions. Both these checks fail for me, and I can't figure out why.
You can create a csv file for opening with spreadsheet software too:
`python wallet-tool.py …
> Wallet history

- broadcast-tx.py
- joinmarket/irc.py
Not many people know that all makers running today are able to broadcast transactions sent to them. This script can be used to ask a maker to broadcast one of your transactions. It's not much more than a proof of concept.
Partly inspired to do this now by threads like this http://www.donotlink.com/i2e5
To add this to takers, blockchaininterface first needs to be edited to have a configurable timeout after which it will invoke a callback as in #118, this is because makers might not broadcast the taker's transaction or there may have been an error. The taker needs to know if the transaction has been seen on the network.
> Created broadcast-tx.py and hacked push_tx() into working

- joinmarket/__init__.py
- joinmarket/enc_wrapper.py
- joinmarket/maker.py
- joinmarket/taker.py
- test/test_enc_wrapper.py
- test/test_irc_messaging.py
Inexplicably I did not do any sanity checking on whether the pubkey/key objects passed into the wrapper functions in enc_wrapper when I set it up.
In this PR there is a placeholder `NaclError` exception type and the pubkeys and keypair objects are checked to be of the right format.
The specific relevance is the `fill` and `pubkey` messages pass a pubkey in hex, now it is checked to be of the right format and if not, the message is ignored. See the edits to the `CoinJoinTx` and `CoinJoinOrder` objects in taker and maker.
There are some tests added also in test_enc_wrapper and in test_irc_messaging (bad `fill`), although not for the exception catch in `CoinJoinTx.start_encryption`. That test is a little tricky to write. Will see if coverage complains or not. And since the crucial point here …
> Catch exceptions in encryption initialization

- joinmarket/blockchaininterface.py
- joinmarket/configure.py
- joinmarket/wallet.py
- test/test_tx_creation.py
Exceeding the absurd value raises a ValueError so is a crash condition. On balance this seems the right choice.
The value is set in the config file, default given, user prompted if it's not present.
> added config absurd_fee_per_kb default 150k sats, and test case

- joinmarket/blockchaininterface.py
Extra line, looks like a merge error
> Fix NotifyThread

- yield-generator-oscillator.py
This change is necessary for compatibility with 32 bit int.  The minimum specification for Python 2.7 int type is 32 bit, and apparently this is not uncommon in Python 2.7 for Windows even when using 64 bit processors. This is only a change to the sanity_check function.
> Allow 'maxsize' and 'minsize' to be type long as well as type int.

- yield-generator-basic.py
- yield-generator-mixdepth.py
In oid_to_order in the yield generator (mixdepth, basic), if there aren't sufficient coins in any mixdepth, `filtered_mix_balance` is set to [], which causes a crash on the call to `filtered_mix_balance[0][0]`
> fix crash on insufficient coins in any mixdepth

- sendpayment.py
The default time to wait for offers to arrive of 5 seconds is too low in some instances.
If I initiate a sendpayment and evaluate the time until the last offers arrive by private message, it sometimes is within 7-10 seconds.
Arguably users connected via TOR sometimes have higher latencies (esp. when both taker and maker are connected via TOR).
Increasing the default therefor might be beneficiary to takers with very little downside:
- pro: possibly more anonymity (late answers will probably be more private users connecting via TOR)
- pro: possibly cheaper joins (late answer could have lower fees)
- con: user has to wait a few more seconds
tumbler.py already has a longer default waiting time and does not need this change.
> sendpayment: increase default waittime from 5 to 15

- sendpayment.py
- tumbler.py
I propose a change of the default maker count from 2-4 to 4-6 (sendpayment) and from median 3 with stdev 1.5 to median 5 with stdev 1.5 (tumbler).
Reasoning:
The first research about JoinMarket ([Join Me on a Market for Anonymity](http://weis2016.econinfosec.org/wp-content/uploads/sites/2/2016/05/WEIS_2016_paper_58.pdf)) has shown that it is possible to increase the costs of a sybil attacker significantly by increasing the maker count, see Table 1 and Table 2 in the paper.
This could already be achieved by takers if they specify their preferred maker count in the command line parameters. Users use joinmarket as taker in search for anonymity for their coins. As many user do not change default values, the default should be set to a more secure value (see Figure 5 in that paper, that the …
> sendpayment/tumbler: increase default maker count

- yield-generator-basic.py
- yield-generator-deluxe.py
- yield-generator-mixdepth.py
Fixes issue #567 
Problematic were these lines: https://github.com/JoinMarket-Org/joinmarket/blob/master/yield-generator-mixdepth.py#L157-161
If a txfee > the dust_threshold was set and maximum size order was requested, no mixdepth could contain enough coins to cover amount+txfee. This mostly wasnt an issue until now because most makers have a txfee=0 or did not even notice, because this does not crash the yieldgen-bot.
So this PR sets the announced maximum order to:
max_coins_in_one_mixdepth - max(dust_threshold, txfee)
> yieldgens: fix issue 567 for max_size orders

- joinmarket/socks.py
As suggested in #543 this PR allows TOR stream isolation by using random username/passwords.
Streams are only isolated when connecting to the clearnet IP address of the irc server though (tested: works).
If the hidden irc service is used, streams are NOT isolated. This is not supported by TOR according to fluffypony from the JM irc channel. Basically: connections to **different** hidden services are isolated by default. Connections to the **same** hidden service **cannot** be isolated.
This will therefor also work nicely for things like connecting to random bitcoin nodes to push transactions anonymously as belcher suggested in #503 .
I think therefor, that there is no downside to this fix.
> socks.py: randomize socks5 credentials for tor stream isolation

- joinmarket/irc.py
- joinmarket/message_channel.py
- test/test_irc_messaging.py
After reports via IRC: receiving privmsgs with 0 length can cause crash; also noticed it will also be possible if message after parsing trailers may cause a crash in on_privmsg in messagechannel. Added checks for this.
> fix crash on short/null privmsg

- joinmarket/irc.py
PR which automatically detects the IRC network name and puts it into self.hostid in MessageChannel.
miniircd doesn't send the NETWORK parameter so to keep our tests working, self.hostid is initalized by data from the host and port, which is then overwritten.
> made irc code detect network name and use it for hostid

- wallet-tool.py
mixdepth-from and mixdepth-to can be tuples, their string representation
contains commas, breaking the csv output for many use cases. Quote all
fields to prevent this and future inconsistencies.
> Quote csv values of wallet-history script

- .travis.yml
- broadcast-tx.py
- create-unsigned-tx.py
- joinmarket/__init__.py
- joinmarket/configure.py
- joinmarket/irc.py
- joinmarket/maker.py
- joinmarket/message_channel.py
- joinmarket/support.py
- joinmarket/taker.py
- sendpayment.py
- test/conftest.py
- test/regtest_joinmarket.cfg
- test/test_broadcast_method.py
- test/test_irc_messaging.py
- test/test_regtest.py
- test/test_tumbler.py
- tumbler.py
- yield-generator-basic.py
- yield-generator-deluxe.py
- yield-generator-mixdepth.py
- yield-generator-oscillator.py
**DO NOT MERGE** - this is now a protocol break as of 6b8fcce
#The goal is to make it transparent to current users - existing config files will still work the same. Adding a new server should be as simple as adding another item in comma separated lists to the config MESSAGING section.
The commit comments give the basic gist of it. Any code review would be great.
I will add some more details later here.
I'll start running it on freenode and cyberguerrilla myself today, probably.
> Facility to use multiple message channels (including IRC servers or other)

- bitcoin/secp256k1_main.py
Note that this is only a partial fix, since bots will crash if they try to execute the donation code (i.e. if choosing non-zero donation as tumbler). Complete fix therefore requires that the underlying secp256k1 binding is up to date with at least 0.13.1, which includes the custom_nonce PR.
> Windows specific fix to allow bots to run with secp256k1 binding.

- joinmarket/yieldgenerator.py
- yg-pe.py
- yield-generator-basic.py
Add a new option `-g` (as with `wallet-tool.py`) for the yield generators that allows controlling the gap limit used in the underlying wallet.
Another try for #613.
> Add gaplimit option for yield generators.

- .coveragerc
- cmttools/add-utxo.py
- joinmarket/__init__.py
- joinmarket/blockchaininterface.py
- joinmarket/yieldgenerator.py
- patientsendpayment.py
- sendpayment.py
- test/test_blockr.py
- test/test_donations.py
- test/test_podle.py
- test/test_regtest.py
- test/test_tumbler.py
- test/test_tx_creation.py
- test/test_tx_notify.py
- test/test_wallets.py
- test/ygrunner.py
- tumbler.py
- wallet-tool.py
Current wallet sync is not smart enough about the situation where a wallet was previously in sync and is now restarting, with index_cache and wallet imports intact.
In practice this was not too important until recently, when spying activity vastly increased the size of used address lists, but it is now a major practical problem.
This adds a `--fast` option to all the scripts that sync the wallet before beginning. Under the hood it uses rpc `listaddressgroupings` to get all of the relevant address data in one call.
Since it is slightly tricky for the code to automatically recognize whether this faster sync can happen successfully, it was decided to leave it as an option which is turned off by default.
Also important is that an attempt to use `--fast` which is unsuccessful will simply …
> add fast sync option for Core wallets

- bitcoin/bci.py
- broadcast-tx.py
- cmttools/sendtomany.py
- create-unsigned-tx.py
- joinmarket/blockchaininterface.py
- joinmarket/configure.py
- joinmarket/irc.py
- joinmarket/maker.py
- joinmarket/message_channel.py
- joinmarket/support.py
- joinmarket/taker.py
- joinmarket/wallet.py
- joinmarket/yieldgenerator.py
- ob-watcher.py
- patientsendpayment.py
- sendpayment.py
- tumbler.py
- yg-pe.py
- yield-generator-basic.py
Currently, this is only intended for users to better understand which log messages are relevant to them.
Change all log.debug() lines in every .py file to the appropriate log level (log.debug(), log.info(), log.warn() or log.error()).
No changes in any program logic. DEBUG is also still default log level for both the console and logfiles.
> Add different log levels

- README.md
Tested with Tails 2.6. Also fixed ordering error in the debian/ubuntu quick install notes
> Add quick install notes for tails

- joinmarket/configure.py
#631 always set the log level to INFO, because the level was checked before the joinmarket.cfg was actually read. This PR puts the log initialization code in the right place.
> Fix bug: configuring log level from joinmarket.cfg now works as intended

- wallet-tool.py
Add a command to `wallet-tool.py` to export a private key without
1. sync the wallet
2. expose all the other private keys.
Example:
`python2 ./wallet-tool.py  wallet.json dumpprivkey -H m/0/4/1/101`
> Dumpprivkey

- README.md
Inspired by https://www.reddit.com/r/joinmarket/comments/5cgy40/pyconfigh_no_such_file_or_directory/
This is a quick change to match that. However, for my own install on a fresh system, I only need:
- gcc
- libsodium13
- python-dev
- virtualenv
I highly recommend that we stop recommending installing to the system python and always recommend using virtualenv instead. Its just too easy to break your system install with pip.
> Fix install deps

- wallet-tool.py
**This adds the total profit from all successfull coinjoins to the history command in wallet-tool**
This is useful because before you had to manually add all deposits and subtract them from the wallet balance. It displays prior to the annual interest rate and will work without numpy installed.
To see the profit enter this command:
> python wallet-tool.py wallet.json history
It looks like this:
> total profit = 0.00020829 BTC
> continuously compounded equivalent annual interest rate = 6.79291165341 %
> Add total profit to history command in wallet-tool

- bitcoin/podle.py
- wallet-tool.py
Enhance showutxos (JoinMarket-Org/joinmarket#656)
Include external utxos
Add `mixdepth`
Add `tries`
Add `tries_remaining`
Add `external` (true/false)
To avoid duplicating the code that checks for the number of tries, added `btc.podle.get_podle_tries()`. This is called from `wallet-tool.py` and `btc.podle.generate_podle()` is refactored to use it.
Renamed `tries` parameter for `btc.podle.generate_podle()` to `max_tries` to avoid confusion.
> Enhance showutxos (JoinMarket-Org/joinmarket#656)

- bitcoin/bci.py
Change user agent to Firefox ESR for improved privacy
Currently user agent is set to a string that (in practice) identifies a request as being from JoinMarket. This is bad for privacy.
This PR changes the user agent to a standard Firefox ESR user agent string. This is what is used by Tor Browser and will help JoinMarket requests blend in more. New ESR releases are made once a year so this will not need to be changed often.
> Change user agent to Firefox ESR for improved privacy

- test/test_wallets.py
- wallet-tool.py
Allows multiple:
`python wallet-tool.py generate`
wallet.json increments to wallet<#>.json checking if available first.
wallet.json wallet1.json etc.
Tests included generating three wallets with default names.
closes #678
> Increments default walletname when wallet already exists

- joinmarket/blockchaininterface.py
- joinmarket/configure.py
- joinmarket/wallet.py
While at it, I also fixed the "don't use N=1 with bitcoin core" (which returns -1 and leads to a hardcoded fee instead of honoring the user's wish to target a REALLY fast confirmation block). It's now handled automatically.
> Allow users to set their own tx fees, as suggested in #657

- patientsendpayment.py
Added some improvements to patientsendpayment, including:
1. Can have many send jobs. It will send an amount of bitcoin to one destination and when that's done it can start sending to another.
1. Can send to many addresses per destination to avoid address reuse, can also accept a xpub BIP32 key.
1. Has all the timeout callback improvements that tumbler and sendpayment have when being a taker.
1. Can be configured to wait forever and never become a taker. (Simple idea but a bit of an oversight before)
Currently in the process of making a wiki page with more details of how to use it.
> improved patientsendpayment now that the new protocol allows it to work

- joinmarket/yieldgenerator.py
- yg-pe.py
- yield-generator-basic.py
The configurable mixdepths never made sense, and tripped up some people. Also the error message lead to lots of confusion in the IRC channel.
> Removed configurable mixdepths from yieldgens, also reworded error message

- joinmarket/__init__.py
- joinmarket/configure.py
- joinmarket/peertopeer.py
- joinmarket/taker.py
- test/commontest.py
- test/test_p2p_protocol.py
Use `tx_broadcast = tor` in joinmarket.cfg to connect to a random bitcoin node on the network, to broadcast a transaction and then disconnect. The DNS seeds are used to find these nodes.
Right now on the bitcoin network, there are an unknown number of sybil nodes which aggressively announce themselves in an effort to attract more people to connect to them. Then they spy on every newly-broadcasted transaction, tracking it as it propagates through the p2p network and giving them a good idea of the IP address that originally broadcasted that transaction.
JoinMarket already had a feature of asking a maker bot to broadcast your transaction, although this isn't as good as using tor. See issue #56 for discussion.
This PR implements #503. It includes code for connecting to a bitcoin node over p2p …
> Tor broadcast method

- joinmarket/configure.py
- test/test_blockr.py
What we previously thought was an absurd miner fee is now the reality.
Bumped up this absurd value to be an order of magnitude higher than the current market fee rate.
Also fixed the test which had hard-coded absurd values, it now uses the absurd values from the joinmarket.cfg file. This is breaking all automated test runs right now. See https://travis-ci.org/JoinMarket-Org/joinmarket/builds/207548542#L1336
> fixed absurd miner fee check

- wallet-tool.py
This feature was requested and it's quick to code so here it is. Intended for automated scripts, people should still use the old method.
`python wallet-tool.py wallet.json importprivkey cli-import-WARNING-DANGEROUS-DONT-USE-WITHOUT-UNDERSTANDING your-private-key-here`
I tested this by importing testnet keys with the old and new method.
I'll also add a how-to for this on the relevant section in the wiki, as well as explaining the danger of how it makes your private key end up in `.bash_history`
> Import privkey non-interactively

- joinmarket/wallet.py
- test/test_wallets.py
- wallet-tool.py
**This allows wallets to have a zero length (`''`) password. (As requested in #674)**
When generating a new wallet and pressing enter both times when you are asked to set a password it will present you with the following warning
```
============= WARNING =============
Using no password is very dangerous
===================================
Abort? [Y/n]
```
To proceed with a empty password you have to confirm with a `n`, pressing enter will stop the generation process.
The wallet checks `''` and if it does not unlock the wallet it will ask the user to input the password.
> Allow no/empty password (Implements #674)

- sendpayment.py
- tumbler.py
See #707 and my comment on it for explanation.
Testing: I'm finding it very difficult to reproduce, I believe this is because it fundamentally depends on the speed with which the db call returns; even with 6 makers x 300 orders each (done by slight tweaks to scripts and running ygrunner/sendpayment) I was only able to reproduce the "Recursive use of cursor" exception once, so not reliably, at least yet.
On the other hand, the test suite passes, so in the case that this *doesn't* solve the observed problem in the live pit (well, I hope it does), I don't see it causing a problem.
> lock db access from taker scripts to avoid cursor exceptions

- joinmarket/yieldgenerator.py
I have an old wallet that has more than the default mix depths. I don't want to spend the transaction fees to move all the coins out of my mix depths over the default.  wallet-tool is smart about expanding the max, but whenever my yield generator updates the wallet, it cuts off any index_cache above the default.
I had a moment of panic where I thought coins were missing until I looked and saw it was only counting the first 5 depths.
This should keep everyone on 5 but keep old wallets working fine.
> Add "extend_mixdepth=True" to yieldgen

- logs/scrub-log.py
The scrub-log.py script failed to delete TXIDs that got dribbled into the log as unicode. Why this happens is not yet fully clear, but it appears to only occur with the `gettxout` RPC call. Problem was spotted by @AdamISZ while [helping a redditor](https://www.reddit.com/r/joinmarket/comments/6oyx3n/strange_maker_logs_not_sure_how_to_explain_at/).
> fix scrub-log.py bug: also scrub unicode TXIDs
