- TODO
- irclib.py
- maker.py
- patientsendpayment.py
- sendpayment.py
- taker.py
- yield-generator.py
As discussed in #5 
(Made a couple of removals/edits from TODO page also)
Tested OK with yieldgen and sendpayment bots.
> remove encryption keyfile persistence

- common.py
- maker.py
- taker.py
Changed command_prefix to be all caps as per #TODO in common.py
> Capitalizing command_prefix

- common.py
- patientsendpayment.py
- sendpayment.py
- taker.py
Changed get_mix_utxo_list to get_utxo_list_by_mixdepth as per #TODO in command.py
> Changed get_mix_utxo_list to get_utxo_list_by_mixdepth

- common.py
- irc.py
- joinmarket.cfg
- patientsendpayment.py
- sendpayment.py
- tumbler.py
- wallet-tool.py
- yield-generator.py
Tested ok with sendpayment and yieldgen.
Config is loaded in each bot (yieldgen, sendpayment, patientsendpayment and tumbler) on startup, at the moment only IRC variables in there, also blockchain stuff which is not being used yet.
> basic config in joinmarket.cfg file

- wallet-tool.py
option --gap-limit N wasn't working due to gap limit being read as str instead of integer, fixed.
> option gaplimit type set to int

- lib/irc.py
- lib/taker.py
Initial sanity checks as per #73
> Sanity check for relorder params

- ob-watcher.py
```
Before:                                         After:
```
> fix depth charts for the case of a lone applicable offer

- ob-watcher.py
Hello,
I ordered the orderbook
Martino
> Sort the orderbook

- lib/common.py
- ob-watcher.py
see commit messages for details
> shed bikes and fix bugs

- yield-generator.py
> bug fix: 'statement_file' is not defined

- lib/blockchaininterface.py
- regtest.py
* Moved test script to regtest.py in main directory (can be moved to a /testing directory later)
* Only other file changed: blockchaininterface.py ; as you can see, apart from changes the RegTestInterface class, there is almost nothing, so impact on live code should be zero.
* One can run the tests in parallel with another (real) joinmarket instance (see port configuration below)
* Tests implemented are rudimentary (2 and 3 party for now, but easily configurable to larger numbers). The purpose of this commit is just to get it working.
* Running requires several setup steps, mainly making a new bitcoin.conf and joinmarket.cfg edits.
* I will detail the steps to run in a wiki article.
> update regtest script

- lib/blockchaininterface.py
> kiss walletnotify listener

- ob-watcher.py
> add ?scale=log to /ordersize

- test/tumbler-test.py
This will not run correctly without default configuration; see edits in [wiki page](https://github.com/chris-belcher/joinmarket/wiki/Testing-2:-testing-the-tumbler-script) for details.
> tumbler test script

- lib/common.py
> Delete leftover print statement in select_greedy

- orderbook.html
I added JS code to highlight lines of the orderbook table. This gives a quicker overview over the interested orders (e.g. your own yield generator).
The selection it's persistent.
> orderbook.html: select specific orders with a single click

- test/regtest.py
- test/regtest_joinmarket.cfg
[![Build Status](https://travis-ci.org/adlai/joinmarket.svg?branch=master)](https://travis-ci.org/adlai/joinmarket)
> Update regtest.py and regtest_joinmarket.cfg

- lib/common.py
- This new algorithm will replace the old "greedy" one
- The old "greedy" one is retained as "greediest".
> Add new algorithm for more precise dust sweeping

- wallet-tool.py
> fix get_p2pk_vbyte() call in import privkeys

- test/wallet-test.py
handling of return codes has changed, previously caused error in wallet-test, fixed.
> fix tests for pexpect v4.0

- yield-generator.py
> prevent crash if there are no new/old absorders

- ob-watcher.py
Top chart is a little lopsided, but still conveys the relevant info:
> add log scale to depth charts (and plot for larger volumes)

- wallet-tool.py
Also, wallet-tool.py gets a new listwallets method
> Do not overwrite existing wallet files when generating wallet. 

- joinmarket/__init__.py
- joinmarket/irc.py
My refactor accidentally unused the local socks implementation.  Fixed.
> fix local socks usage

- joinmarket/irc.py
- sendpayment.py
- test/regtest.py
- test/tumbler-test.py
- wallet-tool.py
- yield-generator-basic.py
- yield-generator-deluxe.py
- yield-generator-mixdepth.py
These ran and completed a test transaction. Changes were for compatibility with latest refactor ( and yapf formatting).
> refactoring for yieldgens

- joinmarket/wallet.py
> fix boolean indexing in wallet

- joinmarket/support.py
- sendpayment.py
(also trims whitespace in sendpayment.py)
Rebase of #342 onto current develop
> Enable manual counterparty selection for sweeping

- .travis.yml
> switch tests to use hostmask-uniquifying miniircd

- README.md
- joinmarket/irc.py
manual test passed in test channel
> Fixcrash, dev

- yield-generator-deluxe.py
> fix issue 395

- yield-generator-deluxe.py
> fix issue #392 (dev)

- joinmarket/maker.py
> recover from selection of spent utxos

- joinmarket/blockchaininterface.py
> Since os.system isn't catching errors anymore, we need to do that

- joinmarket/irc.py
Empirically found parameters that work for cyberguerilla.
Used create-unsigned-tx.py with -N 10 
Use this `print_throttle_msg` flag so the console doesn't get spammed too much.
> Adjust throttle parameters and some others

- sendpayment.py
- randomized default behavior!
- increases complexity of input-output correlation!
- estimated taker-side "fee event": 1.5x - 2x
> bump default makercount to randint(2,4)

- yield-generator-basic.py
> Add absolute fees to yield-generator-basic and command line configuration

- joinmarket/__init__.py
- joinmarket/configure.py
- joinmarket/taker.py
- test/test_broadcast_method.py
> Implemented issue #56, options for broadcasting transactions via makers

- README.md
Change download/install instructions from old release 1.0.3 to new release 1.0.4
> Update README.md for new 1.0.4 release

- README.md
Reverts JoinMarket-Org/joinmarket#512
> Revert "Update README.md for new 1.0.4 release"

- joinmarket/irc.py
Changed exception to warning and logging more verbose message to debug log. No changes in program logic.
Inspired by [this question](https://github.com/JoinMarket-Org/joinmarket/issues/518)
> Update irc.py: improve error message fun check_for_orders

- yield-generator-oscillator.py
> yg-oscill: fix empty filtered_mix_balance crash

- sendpayment.py
- tumbler.py
If the user does not give an initial fee estimation, dynamically estimate the initial fee from the blockchain. Required for non-sweeping sendpayments.
This helps to fix issue #544 . Discussion also in PR #550
> sendpayment / tumbler: dynamic tx fee estimation

- bitcoin/__init__.py
- bitcoin/podle.py
- joinmarket/__init__.py
- joinmarket/configure.py
- joinmarket/maker.py
- joinmarket/message_channel.py
- joinmarket/taker.py
- test/regtest_joinmarket.cfg
Will put together a new test script for this.
> initial working version of PoDLE commitments by takers

- yg-pe.py
minsize option was not honored here for reloffer
> minsize option not honored, bugfix

- joinmarket/irc.py
https://github.com/JoinMarket-Org/joinmarket/issues/619#issuecomment-249370294
> part #agora if connected

- joinmarket/irc.py
add hostid to irc debug logging
> add hostid to irc debug log

- joinmarket/configure.py
https://github.com/JoinMarket-Org/joinmarket/issues/619
> add agora-irc to config

- yg-pe.py
I forked the "develop" branch and then ran `autopep8 -a -a -a -a -i yg-pe.py` and then removed imports that pyflakes told me were unused.
> Autopep8 yg-pe.py

- README.md
Fix the sequence of the installation steps and add "sudo" to the pip-command. Inspired by https://www.reddit.com/r/joinmarket/comments/560n3g/cant_properly_install_02_i_doubt_most_users_will/
> Update debian/ubuntu installation instructions

- joinmarket/message_channel.py
I missed this file/line with https://github.com/JoinMarket-Org/joinmarket/pull/623
> add hostid to debug log

- joinmarket/configure.py
- sendpayment.py
- test/test_regtest.py
- yg-pe.py
- yield-generator-basic.py
Modify default maker count to rand(3,5) from (4,6)
Modify default maker_timeout_sec to 45 from 30 (bigger messages)
Rationale: default relative fee is too high, in tumbler is likely to result in fees ~ 4 (num mixdepths) x 5 (num makers) x .2% which is 4% before bitcoin tx fees which can easily be another percent, for smallish amounts. This is clearly too high (although it's an overestimate, but still). Market experience suggests fees rapidly fall to much lower values.
Note that with default txfee=1000 (admittedly this is almost completely arbitrary nowadays until a new tx fee contribution model is devised), we get a minsize with these defaults of ~ 7 million satoshi; although this is fairly large I am not unhappy with dissuading any trades < 5 million since at that point the bitcoin fee …
> Modify default fee to 0.02%

- test/test_wallets.py
- wallet-tool.py
This resolves #651
Suggestions welcome.
TODO: Add tests
> Adds ability to change encryption password of wallet.json

- wallet-tool.py
Improve wallet tool help format
Ugly hack but I think it is better than what was there.
> Improve wallet tool help format

- README.md
It took me a good while to find it, and was really helpful in making me understand fundamentals.
> Add link to "High level design"

- joinmarket/maker.py
Someone on IRC came saying they got a 4gb log file that filled up their entire disk. The cause was this infinite loop. No idea why they couldn't get a non-stale UTXO but if it ever happens again better to just exit.
This code has tests running against it so if they pass I'd say just merge.
> Removed an infinite loop that resulted in a 4gb log file

- joinmarket/electruminterface.py
Fixed return value of electrum blockchain interface.
Untested by me, but probably works given its simplicity :fingers crossed:
> fixed pushtx return value

- joinmarket/blockchaininterface.py
When joinmarket notices un-imported addresses while synchronizing the wallet history with bitcoind it will re-import all used addresses again. Depending on the age and usage of the joinmarket wallet that can take several hours to complete.
This patch prevents already imported addresses from being re-imported.
> avoid re-importing already imported addesses to bitcoind

- yg-pe.py
Since there's sometimes confusion about what the parameter actually mean, I've added verbose comments to it.
Also:
- remove nickserv_password parameter (not needed any more)
- rename max_minsize to min_minsize as in #700
> yg-pe: Improve yg comments

- yg-pe.py
- yield-generator-basic.py
> fix for minsize > maxsize AssertionError in yield generators

- test/test_p2p_protocol.py
https://github.com/JoinMarket-Org/joinmarket/pull/725#issuecomment-289233705
let's see what the automated testing says
edit: passed
> fix broken p2p test

- bitcoin/secp256k1_main.py
- wallet-tool.py
Signature is compatible with Core (although not much tested yet).
User passes the HD path as an option (-H).
Verification not yet exposed (some complexity in secp256k1 api).
> Message signing with Joinmarket wallet addresses
